// Siderbar Types

// Sidebar Hamburger Menu Toggle States
export const COLLAPSED_STATE = 'COLLAPSED_STATE';

// Sidebar Link States
export const SELECT_DASHBOARD = 'SELECT_DASHBOARD';
export const SELECT_FINANCIAL_POSITION = 'SELECT_FINANCIAL_POSITION';
export const SELECT_PAYEES = 'SELECT_PAYEES';
export const SELECT_GLOBAL_PAYEES = 'SELECT_GLOBAL_PAYEES';
export const SELECT_MEMBERS = 'SELECT_MEMBERS';
export const SELECT_POCKETS = 'SELECT_POCKETS';

// Dashboard States
export const SWITCH_ACTIVE_BUSINESS = 'SWITCH_ACTIVE_BUSINESS';

// Personal Profile States
export const PERSONAL_DETAILS_STATE = 'PERSONAL_DETAILS_STATE';
export const PERSONAL_ADDRESS_STATE = 'PERSONAL_ADDRESS_STATE';
export const IDENTIFICATION_STATE = 'IDENTIFICATION_STATE';

export const SUBMIT_PERSONAL_DETAILS = 'SUBMIT_PERSONAL_DETAILS';
export const SUBMIT_PERSONAL_ADDRESS_DETAILS = 'SUBMIT_PERSONAL_ADDRESS_DETAILS';
export const SUBMIT_IDENTIFICATION_DETAILS = 'SUBMIT_IDENTIFICATION_DETAILS';

// Business Profile States
export const BASIC_INFORMATION_STATE = 'BASIC_INFORMATION_STATE';
export const BUSINESS_ADDRESS_STATE = 'BUSINESS_ADDRESS_STATE';
export const BANK_INFORMATION_STATE = 'BANK_INFORMATION_STATE';
export const INCORPORATION_DETAILS_STATE = 'INCORPORATION_DETAILS_STATE';
export const EXPECTED_USE_STATE = 'EXPECTED_USE_STATE';

export const SUBMIT_BASIC_INFORMATION = 'SUBMIT_BASIC_INFORMATION';
export const SUBMIT_INCORPORATION_DETAILS = 'SUBMIT_INCORPORATION_DETAILS';
export const SUBMIT_EXPECTED_USE_DETAILS = 'SUBMIT_EXPECTED_USE_DETAILS';

// Business Member States
export const ADD_MEMBER = 'ADD_MEMBER';

// Business Member States
export const SUBMIT_MEMBER_PERSONAL_DETAILS = 'SUBMIT_MEMBER_PERSONAL_DETAILS';
export const SUBMIT_MEMBER_PERSONAL_ADDRESS_DETAILS = 'SUBMIT_MEMBER_PERSONAL_ADDRESS_DETAILS';
export const SUBMIT_MEMBER_IDENTIFICATION_DETAILS = 'SUBMIT_MEMBER_IDENTIFICATION_DETAILS';








